/**
 * Export Config Skill for Claude Code
 *
 * Exports LP structure to various formats (YAML, JSON)
 * Usage: export-config --format [yaml|json] --output [file]
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import type { MyVisionLPStructure } from '../types/myvision-lp-patterns';

export interface ExportConfigSkillOptions {
  structure: MyVisionLPStructure;
  format: 'yaml' | 'json';
  outputPath?: string;
  pretty?: boolean;
}

export class ExportConfigSkill {
  name = 'export-config';
  description = 'Export LP structure to YAML or JSON format';

  /**
   * Execute the skill
   */
  async execute(options: ExportConfigSkillOptions): Promise<string> {
    console.log(`📤 Exporting LP structure to ${options.format.toUpperCase()}...\n`);

    const content =
      options.format === 'yaml'
        ? this.toYAML(options.structure, options.pretty)
        : this.toJSON(options.structure, options.pretty);

    if (options.outputPath) {
      const fullPath = join(process.cwd(), options.outputPath);
      writeFileSync(fullPath, content, 'utf-8');
      console.log(`✅ Exported to: ${fullPath}\n`);
    } else {
      console.log('📄 Generated Config:\n');
      console.log(content);
      console.log('');
    }

    return content;
  }

  /**
   * Convert structure to JSON
   */
  private toJSON(structure: MyVisionLPStructure, pretty: boolean = true): string {
    return JSON.stringify(structure, null, pretty ? 2 : 0);
  }

  /**
   * Convert structure to YAML (simplified, manual serialization)
   */
  private toYAML(structure: MyVisionLPStructure, pretty: boolean = true): string {
    const indent = pretty ? 2 : 0;
    const lines: string[] = [];

    // Header
    lines.push('# MyVision LP Structure Configuration');
    lines.push('# Generated by LP Generator Orchestrator');
    lines.push('# Pattern: ' + structure.pattern.id);
    lines.push('');

    // Metadata
    lines.push('metadata:');
    lines.push(`  company_name: "${structure.metadata.company_name}"`);
    lines.push(`  industry: "${structure.metadata.industry}"`);
    if (structure.metadata.established) {
      lines.push(`  established: "${structure.metadata.established}"`);
    }
    lines.push(`  key_competency: "${structure.metadata.key_competency}"`);
    lines.push('');

    // Pattern
    lines.push('pattern:');
    lines.push(`  id: "${structure.pattern.id}"`);
    lines.push(`  target: "${structure.pattern.target}"`);
    lines.push(`  logic_flow: "${structure.pattern.logic_flow}"`);
    lines.push(`  description: "${structure.pattern.description}"`);
    lines.push('');

    // Hero Section
    lines.push('hero_section:');
    lines.push(`  meaning: "${structure.hero_section.meaning}"`);
    lines.push('  catchphrase:');
    lines.push(`    content: "${structure.hero_section.catchphrase.content}"`);
    lines.push(`    logic: "${structure.hero_section.catchphrase.logic}"`);

    if (structure.hero_section.key_metric_salary) {
      lines.push('  key_metric_salary:');
      lines.push(`    value: "${structure.hero_section.key_metric_salary.value}"`);
      lines.push(`    logic: "${structure.hero_section.key_metric_salary.logic}"`);
    }

    if (structure.hero_section.social_proof_count) {
      lines.push('  social_proof_count:');
      lines.push(`    value: "${structure.hero_section.social_proof_count.value}"`);
      lines.push(`    logic: "${structure.hero_section.social_proof_count.logic}"`);
    }

    if (structure.hero_section.trust_indicator_rating) {
      lines.push('  trust_indicator_rating:');
      lines.push(`    value: ${structure.hero_section.trust_indicator_rating.value}`);
      lines.push(`    source: "${structure.hero_section.trust_indicator_rating.source}"`);
      lines.push(`    logic: "${structure.hero_section.trust_indicator_rating.logic}"`);
    }

    lines.push('  primary_cta:');
    lines.push(`    text: "${structure.hero_section.primary_cta.text}"`);
    lines.push(`    link: "${structure.hero_section.primary_cta.link}"`);
    lines.push(`    logic: "${structure.hero_section.primary_cta.logic}"`);
    lines.push('');

    // Trust Builder
    lines.push('trust_builder:');
    lines.push(`  meaning: "${structure.trust_builder.meaning}"`);

    if (structure.trust_builder.partner_logos) {
      lines.push('  partner_logos:');
      lines.push(`    display: "${structure.trust_builder.partner_logos.display}"`);
      lines.push('    firms:');
      structure.trust_builder.partner_logos.firms.forEach(firm => {
        lines.push(`      - "${firm}"`);
      });
      lines.push(`    logic: "${structure.trust_builder.partner_logos.logic}"`);
    }

    if (structure.trust_builder.consultant_profiles) {
      lines.push('  consultant_profiles:');
      lines.push('    profiles:');
      structure.trust_builder.consultant_profiles.profiles.forEach(profile => {
        lines.push(`      - name: "${profile.name}"`);
        lines.push(`        previous_company: "${profile.previous_company}"`);
        lines.push(`        title: "${profile.title}"`);
        lines.push(`        specialties: [${profile.specialties.map(s => `"${s}"`).join(', ')}]`);
      });
      lines.push(`    logic: "${structure.trust_builder.consultant_profiles.logic}"`);
    }
    lines.push('');

    // Service Differentiation
    lines.push('service_differentiation:');
    lines.push(`  meaning: "${structure.service_differentiation.meaning}"`);

    if (structure.service_differentiation.proprietary_materials) {
      lines.push('  proprietary_materials:');
      lines.push('    items:');
      structure.service_differentiation.proprietary_materials.items.forEach(item => {
        lines.push(`      - "${item}"`);
      });
      lines.push(`    logic: "${structure.service_differentiation.proprietary_materials.logic}"`);
    }

    if (structure.service_differentiation.mock_interviews) {
      lines.push('  mock_interviews:');
      lines.push(
        `    description: "${structure.service_differentiation.mock_interviews.description}"`
      );
      lines.push(`    unlimited: ${structure.service_differentiation.mock_interviews.unlimited}`);
      lines.push(`    logic: "${structure.service_differentiation.mock_interviews.logic}"`);
    }
    lines.push('');

    // Success Data Repository (optional)
    if (structure.success_data_repository) {
      lines.push('success_data_repository:');
      lines.push(`  meaning: "${structure.success_data_repository.meaning}"`);
      lines.push(`  title: "${structure.success_data_repository.title}"`);
      lines.push('  cases:');
      structure.success_data_repository.cases.forEach(case_ => {
        lines.push(`    - age: ${case_.age}`);
        lines.push(`      previous_industry: "${case_.previous_industry}"`);
        lines.push(`      previous_role: "${case_.previous_role}"`);
        lines.push(`      current_firm: "${case_.current_firm}"`);
        if (case_.salary_increase) {
          lines.push(`      salary_increase: "${case_.salary_increase}"`);
        }
      });
      lines.push(`  logic: "${structure.success_data_repository.logic}"`);
      lines.push('');
    }

    // Conversion Optimizer
    lines.push('conversion_optimizer:');
    lines.push(`  meaning: "${structure.conversion_optimizer.meaning}"`);
    lines.push('  final_cta:');
    lines.push(`    label: "${structure.conversion_optimizer.final_cta.label}"`);
    if (structure.conversion_optimizer.final_cta.description) {
      lines.push(`    description: "${structure.conversion_optimizer.final_cta.description}"`);
    }
    lines.push(`    logic: "${structure.conversion_optimizer.final_cta.logic}"`);
    lines.push('');

    // System Integration (optional)
    if (structure.system_integration) {
      lines.push('system_integration:');
      if (structure.system_integration.tracking) {
        lines.push(`  tracking: "${structure.system_integration.tracking}"`);
      }
      if (structure.system_integration.ab_testing) {
        lines.push(`  ab_testing: "${structure.system_integration.ab_testing}"`);
      }
      if (structure.system_integration.data_feed) {
        lines.push(`  data_feed: "${structure.system_integration.data_feed}"`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Validate exported config
   */
  validate(content: string, format: 'yaml' | 'json'): boolean {
    try {
      if (format === 'json') {
        JSON.parse(content);
      }
      // YAML validation would require external library
      return true;
    } catch {
      return false;
    }
  }
}

// Export singleton
export const exportConfigSkill = new ExportConfigSkill();
